# Define an array of symbolic link sources and targets
# $(pwd)/zsh/custom.zsh:$HOME/.config/zsh/custom.zsh
# $(pwd)/zsh/aliases.zsh:$HOME/.config/zsh/aliases.zsh
#$(pwd)/zsh/git-completion.bash:$HOME/.config/zsh/git-completion.bash
#$(pwd)/zsh/git-completion.zsh:$HOME/.config/zsh/git-completion.zsh

$(pwd)/zsh/.zshrc:$HOME/.zshrc
$(pwd)/wezterm/.wezterm.lua:$HOME/.wezterm.lua
$(pwd)/nvim:$HOME/.config/nvim
$(pwd)/ghostty:$HOME/.config/ghostty
$(pwd)/aerospace/.aerospace.toml:$HOME/.aerospace.toml
$(pwd)/sketchybar:$HOME/.config/sketchybar
$(pwd)/zellij:$HOME/.config/zellij
$(pwd)/alacritty:$HOME/.config/alacritty
