#!/bin/bash

echo "Updating zellij-forgot..."
curl -L "https://github.com/karimould/zellij-forgot/releases/latest/download/zellij_forgot.wasm" -o ~/.config/zellij/zellij_forgot.wasm
curl -L "https://github.com/dj95/zjstatus/releases/latest/download/zjstatus.wasm" -o ~/.config/zellij/zjstatus.wasm
echo "All plugins updated!"
